name: Test timestamp=

on:
  workflow_dispatch:
    inputs:
      timestamp:
        type: string
        required: false
        description: "Timestamp to reproduce build. Keep empty to use a generated one. Expected format is: YYYYMMDD_HHmmSS"

jobs:
  get-timestamp:
    name: Get timestamp from input or generate one. Do not re-run when timestamp input is empty, to preserve the generated one.
    runs-on: ubuntu-22.04
    outputs:
      timestamp: ${{ inputs.timestamp || steps.set-timestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp
        id: set-timestamp
        if: ${{ inputs.timestamp == null }}
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
  echo-timestamp:
    runs-on: ubuntu-22.04
    needs: get-timestamp
    steps:
      - name: Echo timestamp
        run: echo "Timestamp ${{ needs.get-timestamp.outputs.timestamp }}"
